image: Ubuntu1804
stack: node 18
branches:
  only: 
    - master
cache: node_modules
install:
  - npm install
build_script:
  - npm run build   # команда сборки
test_script:
  - npm run lint && npm run coverage
